# Generated by Django 4.2.5 on 2023-10-30 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Servicio')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Trabajo a realizar')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trabajo a realizar',
                'verbose_name_plural': 'Trabajos a realizar',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Empleado')),
                ('description', models.TextField(verbose_name='Empleado que llevara a cabo el trabajo')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Deficiente'), (2, 'Necesita mejora'), (3, 'Aceptable'), (4, 'Bueno'), (5, 'Excelente')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='valoraciones', verbose_name='Foto del trabajo realizado')),
                ('fechaservicio', models.SmallIntegerField(blank=True, verbose_name='Fecha')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('servicio', models.ManyToManyField(to='GGTec.servicio', verbose_name='Servicios')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GGTec.trabajo', verbose_name='Trabajo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
