# Generated by Django 4.2.5 on 2023-10-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GGTec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fechaservicio',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='description',
            field=models.TextField(verbose_name='Desempeño'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='valoraciones', verbose_name='Trabajos realizados'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='servicio',
            field=models.ManyToManyField(to='GGTec.trabajo', verbose_name='Trabajos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GGTec.servicio', verbose_name='Servicio'),
        ),
    ]
