# Generated by Django 4.2.5 on 2023-10-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GGTec', '0003_alter_empleado_servicio_alter_empleado_trabajo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trabajo',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='trabajo',
        ),
        migrations.AddField(
            model_name='empleado',
            name='servicios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GGTec.servicio', verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='trabajos',
            field=models.ManyToManyField(to='GGTec.trabajo', verbose_name='Trabajos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Deficiente'), (2, 'A mejorar'), (3, 'Aceptable'), (4, 'Bueno'), (5, 'Excelente')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Compañía'),
        ),
    ]
