# Generated by Django 4.2.5 on 2023-10-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGTec', '0004_alter_empleado_options_alter_trabajo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='servicios',
            new_name='servicio',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='slug',
        ),
    ]
