# Generated by Django 4.2.5 on 2023-10-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGTec', '0006_alter_empleado_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='rating',
            new_name='rating1',
        ),
        migrations.AddField(
            model_name='empleado',
            name='rating2',
            field=models.PositiveSmallIntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$')], null=True),
        ),
    ]
