# Generated by Django 4.2.5 on 2023-10-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGTec', '0007_rename_rating_empleado_rating1_empleado_rating2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='rating2',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='rating1',
            new_name='valoracion',
        ),
    ]
