# Generated by Django 4.2.5 on 2023-10-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGTec', '0008_rename_rating2_empleado_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contacto',
            field=models.TextField(null=True, verbose_name='Contacto'),
        ),
    ]
