# Generated by Django 4.2.5 on 2023-11-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GGTec', '0009_empleado_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='costo',
            field=models.PositiveSmallIntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Empleado/s o Empresa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GGTec.servicio', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Trabajo'),
        ),
    ]
